# Generated by Django 5.2.8 on 2026-01-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10),
        ),
    ]
