# Generated by Django 5.2.10 on 2026-01-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_review_is_hidden_review_sentiment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='review',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='Admin Response'),
        ),
    ]
