# Generated by Django 5.2.8 on 2026-01-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_options_review_admin_note'),
        ('products', '0010_flashsale'),
    ]

    operations = [
    ]
