# Generated by Django 5.2.8 on 2026-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_merge_20260128_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='review',
            name='admin_note',
        ),
        migrations.AddField(
            model_name='flashsale',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
